import type { Question } from '../types';

export const aimlQuestions: Question[] = [
    {
        id: 'aiml-1',
        category: 'aiml',
        difficulty: 'Easy',
        prompt: 'What is supervised learning?',
        options: [
            'Learning from labeled input-output pairs to predict outputs for new inputs',
            'Learning with no labels by finding structure in data',
            'Learning by trial and error with rewards',
            'Learning by imitating a teacher network',
        ],
        correctIndex: 0,
        explanation: 'In supervised learning the dataset has input features and target labels; the model learns a mapping that generalizes to unseen inputs (classification/regression).',
        xp: 10,
    },
    {
        id: 'aiml-2',
        category: 'aiml',
        difficulty: 'Easy',
        prompt: 'Which task predicts a continuous numeric value?',
        options: ['Classification', 'Regression', 'Clustering', 'Reinforcement learning'],
        correctIndex: 1,
        explanation: 'Regression predicts continuous outputs (e.g. house price). Classification predicts discrete labels.',
        xp: 10,
    },
    {
        id: 'aiml-3',
        category: 'aiml',
        difficulty: 'Easy',
        prompt: 'What does a neural network "activation function" do?',
        options: [
            'Introduces non-linearity into the network',
            'Normalizes the input dataset',
            'Counts the training examples',
            'Saves the model to disk',
        ],
        correctIndex: 0,
        explanation: 'Activation functions (ReLU, sigmoid, tanh) apply a non-linear transform to the weighted sum, letting the network model non-linear functions.',
        xp: 10,
    },
    {
        id: 'aiml-4',
        category: 'aiml',
        difficulty: 'Medium',
        prompt: 'What is gradient descent?',
        options: [
            'An optimization method that updates parameters against the gradient of the loss',
            'A data preprocessing technique',
            'A way to split train/test data',
            'A type of neural network layer',
        ],
        correctIndex: 0,
        explanation: 'Gradient descent iteratively moves parameters in the direction that reduces the loss, by stepping opposite to the gradient with a learning rate.',
        xp: 20,
    },
    {
        id: 'aiml-5',
        category: 'aiml',
        difficulty: 'Medium',
        prompt: 'What is overfitting?',
        options: [
            'The model fits training data very well but generalizes poorly to new data',
            'The model under-performs on both train and test data',
            'The dataset is too small to train',
            'The learning rate is too low',
        ],
        correctIndex: 0,
        explanation: 'Overfitting means the model has learned noise/peculiarities of the training set, yielding low training error but high validation/test error. Underfitting is the opposite.',
        xp: 20,
    },
    {
        id: 'aiml-6',
        category: 'aiml',
        difficulty: 'Medium',
        prompt: 'What does the "learning rate" control?',
        options: [
            'The size of each parameter update step during training',
            'How many layers the network has',
            'The size of the training dataset',
            'The number of classes predicted',
        ],
        correctIndex: 0,
        explanation: 'The learning rate scales the gradient step. Too large can diverge; too small can be slow or stuck. It is a key hyperparameter.',
        xp: 20,
    },
    {
        id: 'aiml-7',
        category: 'aiml',
        difficulty: 'Hard',
        prompt: 'What is the vanishing gradient problem in deep networks?',
        options: [
            'Gradients shrink toward zero as they are backpropagated, stalling learning in early layers',
            'Gradients explode to infinity',
            'The model runs out of training data',
            'The learning rate becomes negative',
        ],
        correctIndex: 0,
        explanation: 'In deep nets with saturating activations, repeated multiplication during backprop shrinks gradients to near zero, so early layers barely update. ReLU, residual connections, and batch norm help.',
        xp: 30,
    },
    {
        id: 'aiml-8',
        category: 'aiml',
        difficulty: 'Hard',
        prompt: 'What is the core idea of a Transformer architecture?',
        options: [
            'Self-attention lets every token attend to every other token, dispensing with recurrence',
            'It processes images one pixel at a time with convolution',
            'It stores all training examples and uses k-NN',
            'It encodes rules written by hand',
        ],
        correctIndex: 0,
        explanation: 'Transformers use self-attention to model pairwise interactions across the whole sequence in parallel, replacing RNN recurrence and enabling models like GPT/BERT.',
        xp: 30,
    },
    {
        id: 'aiml-9',
        category: 'aiml',
        difficulty: 'Easy',
        prompt: 'Which library is most commonly used for machine learning in Python?',
        options: [
            'Scikit-learn',
            'Bootstrap',
            'Express.js',
            'Hibernate',
        ],
        correctIndex: 0,
        explanation: 'Scikit-learn provides many machine learning algorithms such as SVM, Decision Trees, Random Forests, and K-Means.',
        xp: 10,
    },
    {
        id: 'aiml-10',
        category: 'aiml',
        difficulty: 'Easy',
        prompt: 'Which algorithm is commonly used for grouping similar data points?',
        options: [
            'Linear Regression',
            'K-Means Clustering',
            'Decision Tree',
            'Naive Bayes',
        ],
        correctIndex: 1,
        explanation: 'K-Means is one of the most popular unsupervised clustering algorithms.',
        xp: 10,
    },

    {
        id: 'aiml-11',
        category: 'aiml',
        difficulty: 'Medium',
        prompt: 'Which evaluation metric is most suitable for imbalanced classification datasets?',
        options: [
            'Accuracy',
            'F1 Score',
            'Mean Squared Error',
            'R² Score',
        ],
        correctIndex: 1,
        explanation: 'F1 Score balances precision and recall, making it better than accuracy for imbalanced datasets.',
        xp: 20,
    },
    {
        id: 'aiml-12',
        category: 'aiml',
        difficulty: 'Medium',
        prompt: 'What is the purpose of train-test split?',
        options: [
            'To increase dataset size',
            'To evaluate model performance on unseen data',
            'To improve GPU performance',
            'To reduce memory usage',
        ],
        correctIndex: 1,
        explanation: 'Separating training and testing data helps estimate how well the model generalizes.',
        xp: 20,
    },

    {
        id: 'aiml-13',
        category: 'aiml',
        difficulty: 'Hard',
        prompt: 'Why is Batch Normalization used in deep neural networks?',
        options: [
            'To reduce internal covariate shift and stabilize training',
            'To compress the dataset',
            'To increase the number of neurons',
            'To replace activation functions',
        ],
        correctIndex: 0,
        explanation: 'Batch Normalization normalizes intermediate activations, resulting in faster and more stable training.',
        xp: 30,
    },
    {
        id: 'aiml-14',
        category: 'aiml',
        difficulty: 'Hard',
        prompt: 'Which optimization algorithm adapts learning rates for individual parameters?',
        options: [
            'Gradient Descent',
            'Adam',
            'Linear Regression',
            'KNN',
        ],
        correctIndex: 1,
        explanation: 'Adam combines momentum and adaptive learning rates, making it one of the most widely used optimizers.',
        xp: 30,
    },
    {
        id: 'aiml-15',
        category: 'aiml',
        difficulty: 'Hard',
        prompt: 'What is the main purpose of attention mechanisms in deep learning?',
        options: [
            'Reduce dataset size',
            'Allow the model to focus on the most relevant parts of the input',
            'Increase image resolution',
            'Prevent overfitting by removing neurons',
        ],
        correctIndex: 1,
        explanation: 'Attention mechanisms help models selectively focus on important information, significantly improving tasks such as translation and text generation.',
        xp: 30,
    },
];
