import type { Question } from '../types';

export const cppQuestions: Question[] = [
    {
        id: 'cpp-1',
        category: 'cpp',
        difficulty: 'Easy',
        prompt: 'Which header is needed for std::cout?',
        options: ['<stdio>', '<iostream>', '<conio>', '<output>'],
        correctIndex: 1,
        explanation: 'std::cout and std::cin are declared in the <iostream> standard library header.',
        xp: 10,
    },
    {
        id: 'cpp-2',
        category: 'cpp',
        difficulty: 'Easy',
        prompt: 'Which operator is used to access members through a pointer?',
        options: ['.', '->', '::', ':'],
        correctIndex: 1,
        explanation: 'The arrow operator -> dereferences a pointer and accesses a member in one step. The dot . is used on objects directly.',
        xp: 10,
    },
    {
        id: 'cpp-3',
        category: 'cpp',
        difficulty: 'Easy',
        prompt: 'What does `delete` do (for a single object allocated with new)?',
        options: [
            'Destroys the object and frees the allocated memory',
            'Removes the variable name from the symbol table',
            'Garbage-collects the entire heap',
            'Marks the pointer as null automatically',
        ],
        correctIndex: 0,
        explanation: 'delete calls the destructor and returns the memory to the free store. It does not set the pointer to nullptr; you must do that yourself.',
        xp: 10,
    },
    {
        id: 'cpp-4',
        category: 'cpp',
        difficulty: 'Medium',
        prompt: 'What is a smart pointer?',
        options: [
            'A pointer with compile-time bounds checking only',
            'A RAII wrapper that manages memory and deletes automatically',
            'A pointer that can point to any type without casts',
            'A synonym for void*',
        ],
        correctIndex: 1,
        explanation: 'Smart pointers (std::unique_ptr, std::shared_ptr, std::weak_ptr) use RAII to own a resource and release it automatically, preventing leaks.',
        xp: 20,
    },
    {
        id: 'cpp-5',
        category: 'cpp',
        difficulty: 'Medium',
        prompt: 'What is the main difference between a struct and a class in C++?',
        options: [
            'No difference at all',
            'Default member access: struct is public, class is private',
            'A struct cannot have methods',
            'A class cannot be instantiated on the stack',
        ],
        correctIndex: 1,
        explanation: 'The only technical difference is the default access: public for struct, private for class. Otherwise they are identical (methods, inheritance, etc.).',
        xp: 20,
    },
    {
        id: 'cpp-6',
        category: 'cpp',
        difficulty: 'Medium',
        prompt: 'What is a virtual function?',
        options: [
            'A function declared in a header but not defined',
            'A member function that supports dynamic (runtime) dispatch',
            'A function that cannot be inlined',
            'A function removed by the optimizer',
        ],
        correctIndex: 1,
        explanation: 'virtual enables runtime polymorphism: the actual override is chosen based on the dynamic type of the object, not the static pointer type.',
        xp: 20,
    },
    {
        id: 'cpp-7',
        category: 'cpp',
        difficulty: 'Hard',
        prompt: 'What is undefined behavior (UB) in C++?',
        options: [
            'A compiler warning that can be ignored',
            'Code for which the standard imposes no requirements, allowing any result',
            'A function declared without a body',
            'A class with no public members',
        ],
        correctIndex: 1,
        explanation: 'UB (e.g. dereferencing a null pointer, signed overflow, use-after-free) means the standard places no constraints — the compiler may do anything, including surprising optimizations.',
        xp: 30,
    },
    {
        id: 'cpp-8',
        category: 'cpp',
        difficulty: 'Hard',
        prompt: 'What is a pure virtual function and what does it make its class?',
        options: [
            '`= 0` declaration; it makes the class abstract and non-instantiable',
            'A function with no return type; it makes the class final',
            'A function deleted with `= delete`; it makes the class a union',
            'A function declared `inline`; it makes the class a POD',
        ],
        correctIndex: 0,
        explanation: 'A pure virtual function (`virtual void f() = 0;`) has no implementation in the base and makes the class abstract — it cannot be instantiated; derived classes must override it.',
        xp: 30,
    },
    {
        id: 'cpp-9',
        category: 'cpp',
        difficulty: 'Easy',
        prompt: 'Which STL container stores unique elements in sorted order?',
        options: [
            'vector',
            'set',
            'unordered_map',
            'queue',
        ],
        correctIndex: 1,
        explanation: 'std::set stores unique elements in sorted order using a balanced tree.',
        xp: 10,
    },
    {
        id: 'cpp-10',
        category: 'cpp',
        difficulty: 'Easy',
        prompt: 'Which OOP principle allows a derived class to acquire properties and behavior of a base class?',
        options: [
            'Encapsulation',
            'Inheritance',
            'Polymorphism',
            'Abstraction',
        ],
        correctIndex: 1,
        explanation: 'Inheritance allows a derived class to reuse and extend the functionality of a base class.',
        xp: 10,
    },

    {
        id: 'cpp-11',
        category: 'cpp',
        difficulty: 'Medium',
        prompt: 'What is the time complexity of searching in std::unordered_map on average?',
        options: [
            'O(log n)',
            'O(n)',
            'O(1)',
            'O(n log n)',
        ],
        correctIndex: 2,
        explanation: 'unordered_map uses hashing, providing average O(1) lookup time.',
        xp: 20,
    },
    {
        id: 'cpp-12',
        category: 'cpp',
        difficulty: 'Medium',
        prompt: 'What is move semantics in C++?',
        options: [
            'Copying objects using memcpy',
            'Transferring ownership of resources instead of copying them',
            'Moving objects to heap memory',
            'Swapping two variables',
        ],
        correctIndex: 1,
        explanation: 'Move semantics transfer ownership of resources, reducing unnecessary copies and improving performance.',
        xp: 20,
    },

    {
        id: 'cpp-13',
        category: 'cpp',
        difficulty: 'Hard',
        prompt: 'Why should a base class destructor often be declared virtual?',
        options: [
            'To enable function overloading',
            'To ensure derived class destructors are called correctly through base pointers',
            'To improve execution speed',
            'To reduce object size',
        ],
        correctIndex: 1,
        explanation: 'Without a virtual destructor, deleting a derived object through a base pointer causes undefined behavior.',
        xp: 30,
    },
    {
        id: 'cpp-14',
        category: 'cpp',
        difficulty: 'Hard',
        prompt: 'What does the noexcept specifier indicate?',
        options: [
            'The function cannot be overloaded',
            'The function is guaranteed not to throw exceptions',
            'The function always returns nullptr',
            'The function executes in constant time',
        ],
        correctIndex: 1,
        explanation: 'noexcept informs the compiler that a function is not expected to throw exceptions, enabling optimizations.',
        xp: 30,
    },
    {
        id: 'cpp-15',
        category: 'cpp',
        difficulty: 'Hard',
        prompt: 'Which statement correctly describes compile-time and runtime polymorphism in C++?',
        options: [
            'Function overloading is compile-time polymorphism, while virtual functions enable runtime polymorphism.',
            'Both are runtime polymorphism.',
            'Both are compile-time polymorphism.',
            'Virtual functions enable compile-time polymorphism.',
        ],
        correctIndex: 0,
        explanation: 'Compile-time polymorphism is achieved using function/operator overloading, whereas runtime polymorphism is achieved using virtual functions and method overriding.',
        xp: 30,
    },
];
