import type { Question } from '../types';

export const dbmsQuestions: Question[] = [
    {
        id: 'dbms-1',
        category: 'dbms',
        difficulty: 'Easy',
        prompt: 'What does ACID stand for in the context of transactions?',
        options: [
            'Atomicity, Consistency, Isolation, Durability',
            'Accuracy, Concurrency, Identity, Data',
            'Atomic, Concurrent, Isolated, Distributed',
            'Access, Control, Integrity, Data',
        ],
        correctIndex: 0,
        explanation: 'ACID = Atomicity (all or nothing), Consistency (valid state to valid state), Isolation (concurrent txns behave independently), Durability (committed changes survive crashes).',
        xp: 10,
    },
    {
        id: 'dbms-2',
        category: 'dbms',
        difficulty: 'Easy',
        prompt: 'Which normal form removes partial dependencies on a composite primary key?',
        options: ['1NF', '2NF', '3NF', 'BCNF'],
        correctIndex: 1,
        explanation: '2NF requires every non-prime attribute to depend on the whole primary key, eliminating partial dependencies (1NF already met).',
        xp: 10,
    },
    {
        id: 'dbms-3',
        category: 'dbms',
        difficulty: 'Easy',
        prompt: 'A foreign key is used to...',
        options: [
            'Encrypt a column',
            'Establish a referential link to a primary key in another table',
            'Speed up sorting',
            'Mark a column as read-only',
        ],
        correctIndex: 1,
        explanation: 'A foreign key references the primary key of another (or the same) table, enforcing referential integrity between related rows.',
        xp: 10,
    },
    {
        id: 'dbms-4',
        category: 'dbms',
        difficulty: 'Medium',
        prompt: 'What is a B+ tree index optimized for?',
        options: [
            'Storing images',
            'Range queries and ordered sequential access on disk',
            'In-memory hash lookups only',
            'Compressing JSON documents',
        ],
        correctIndex: 1,
        explanation: 'B+ trees keep data in sorted leaf pages linked sequentially, making both point lookups and range scans efficient on disk-based storage.',
        xp: 20,
    },
    {
        id: 'dbms-5',
        category: 'dbms',
        difficulty: 'Medium',
        prompt: 'What is the main advantage of a database index?',
        options: [
            'Faster read/lookup performance at the cost of extra storage and slower writes',
            'Smaller database files',
            'Automatic data encryption',
            'Eliminating the need for a primary key',
        ],
        correctIndex: 0,
        explanation: 'Indexes speed up queries but add storage overhead and must be updated on writes, so they trade read performance for write cost.',
        xp: 20,
    },
    {
        id: 'dbms-6',
        category: 'dbms',
        difficulty: 'Medium',
        prompt: 'What does the "Isolation" in ACID guarantee?',
        options: [
            'Concurrent transactions appear to execute serially (per the chosen isolation level)',
            'Each transaction is stored in a separate database',
            'Only one user can connect at a time',
            'Transactions are encrypted in isolation',
        ],
        correctIndex: 0,
        explanation: 'Isolation defines how/when changes made by one transaction become visible to others; higher levels (serializable) make concurrent execution appear serial.',
        xp: 20,
    },
    {
        id: 'dbms-7',
        category: 'dbms',
        difficulty: 'Hard',
        prompt: 'What is a "dirty read"?',
        options: [
            'Reading uncommitted data written by another transaction that may later roll back',
            'Reading from an unindexed table',
            'Reading deleted rows',
            'Reading a corrupted disk block',
        ],
        correctIndex: 0,
        explanation: 'A dirty read occurs at low isolation levels when a transaction reads another transaction uncommitted write, which may be rolled back, yielding data that was never "real".',
        xp: 30,
    },
    {
        id: 'dbms-8',
        category: 'dbms',
        difficulty: 'Hard',
        prompt: 'When is BCNF stronger than 3NF?',
        options: [
            'When every determinant is a candidate key, even if it breaks 3NF dependency preservation',
            'When the table has no foreign keys',
            'BCNF is always weaker than 3NF',
            'Only for tables with a single column',
        ],
        correctIndex: 0,
        explanation: 'Boyce-Codd Normal Form requires every non-trivial functional dependency determinant to be a superkey; it is stricter than 3NF but may not always preserve dependencies.',
        xp: 30,
    },
    {
        id: 'dbms-9',
        category: 'dbms',
        difficulty: 'Easy',
        prompt: 'Which SQL statement is used to retrieve data from a database?',
        options: [
            'SELECT',
            'INSERT',
            'UPDATE',
            'DELETE',
        ],
        correctIndex: 0,
        explanation: 'The SELECT statement is used to retrieve records from one or more database tables.',
        xp: 10,
    },
    {
        id: 'dbms-10',
        category: 'dbms',
        difficulty: 'Easy',
        prompt: 'Which SQL clause is used to filter rows based on a condition?',
        options: [
            'GROUP BY',
            'HAVING',
            'WHERE',
            'ORDER BY',
        ],
        correctIndex: 2,
        explanation: 'The WHERE clause filters rows before grouping or ordering takes place.',
        xp: 10,
    },

    {
        id: 'dbms-11',
        category: 'dbms',
        difficulty: 'Medium',
        prompt: 'What is the main purpose of normalization?',
        options: [
            'Increase database size',
            'Reduce redundancy and improve data consistency',
            'Improve internet speed',
            'Encrypt database records',
        ],
        correctIndex: 1,
        explanation: 'Normalization organizes tables to minimize redundancy and avoid update anomalies.',
        xp: 20,
    },
    {
        id: 'dbms-12',
        category: 'dbms',
        difficulty: 'Medium',
        prompt: 'What is the difference between WHERE and HAVING in SQL?',
        options: [
            'WHERE filters rows before grouping, HAVING filters groups after aggregation',
            'HAVING filters rows, WHERE filters groups',
            'Both perform exactly the same task',
            'HAVING is used only with UPDATE queries',
        ],
        correctIndex: 0,
        explanation: 'WHERE filters individual rows before GROUP BY, while HAVING filters grouped results after aggregation.',
        xp: 20,
    },

    {
        id: 'dbms-13',
        category: 'dbms',
        difficulty: 'Hard',
        prompt: 'Which isolation level completely prevents dirty reads, non-repeatable reads, and phantom reads?',
        options: [
            'Read Uncommitted',
            'Read Committed',
            'Repeatable Read',
            'Serializable',
        ],
        correctIndex: 3,
        explanation: 'Serializable is the highest isolation level and prevents all common concurrency anomalies.',
        xp: 30,
    },
    {
        id: 'dbms-14',
        category: 'dbms',
        difficulty: 'Hard',
        prompt: 'What is a deadlock in DBMS?',
        options: [
            'A database crash caused by power failure',
            'Two or more transactions waiting indefinitely for each other to release resources',
            'A corrupted database index',
            'A transaction that takes too long to execute',
        ],
        correctIndex: 1,
        explanation: 'A deadlock occurs when transactions hold locks while waiting for each other, preventing progress.',
        xp: 30,
    },
    {
        id: 'dbms-15',
        category: 'dbms',
        difficulty: 'Hard',
        prompt: 'What is conflict serializability in DBMS?',
        options: [
            'A schedule equivalent to some serial schedule by swapping non-conflicting operations',
            'Running all transactions simultaneously without locks',
            'Executing transactions alphabetically',
            'Executing only one transaction at a time',
        ],
        correctIndex: 0,
        explanation: 'Conflict serializability ensures concurrent execution produces the same result as some serial execution by preserving the order of conflicting operations.',
        xp: 30,
    },
];
