import type { Question } from '../types';

export const javaQuestions: Question[] = [
    {
        id: 'java-1',
        category: 'java',
        difficulty: 'Easy',
        prompt: 'Which keyword is used to inherit a class in Java?',
        options: ['extends', 'implements', 'inherits', 'super'],
        correctIndex: 0,
        explanation: '`extends` is used for class inheritance. `implements` is for interfaces.',
        xp: 10,
    },
    {
        id: 'java-2',
        category: 'java',
        difficulty: 'Easy',
        prompt: 'What is the parent class of every Java class that does not explicitly extend another?',
        options: ['Class', 'Object', 'Parent', 'Base'],
        correctIndex: 1,
        explanation: 'Every class implicitly extends java.lang.Object if it has no other superclass, which is why methods like toString() and equals() are always available.',
        xp: 10,
    },
    {
        id: 'java-3',
        category: 'java',
        difficulty: 'Easy',
        prompt: 'Which data type is NOT a Java primitive?',
        options: ['int', 'boolean', 'String', 'double'],
        correctIndex: 2,
        explanation: 'String is a reference type (java.lang.String), not a primitive. The 8 primitives are byte, short, int, long, float, double, char, boolean.',
        xp: 10,
    },
    {
        id: 'java-4',
        category: 'java',
        difficulty: 'Medium',
        prompt: 'What does the `final` keyword do when applied to a variable?',
        options: [
            'Makes the variable a constant that can be assigned only once',
            'Prevents the variable from being garbage collected',
            'Forces the variable to be public',
            'Declares the variable as a primitive',
        ],
        correctIndex: 0,
        explanation: 'A final variable can be assigned exactly once. For object references, final means the reference cannot be reassigned, though the object itself may still mutate.',
        xp: 20,
    },
    {
        id: 'java-5',
        category: 'java',
        difficulty: 'Medium',
        prompt: 'What is the JVM?',
        options: [
            'A compiler that produces native machine code',
            'A runtime virtual machine that executes Java bytecode',
            'A Java versioning manager',
            'A package manager for Java libraries',
        ],
        correctIndex: 1,
        explanation: 'The Java Virtual Machine executes compiled bytecode (.class files), providing platform independence and features like garbage collection.',
        xp: 20,
    },
    {
        id: 'java-6',
        category: 'java',
        difficulty: 'Medium',
        prompt: 'What is the key difference between an interface and an abstract class?',
        options: [
            'There is no difference',
            'A class can implement multiple interfaces but extend only one abstract class',
            'Interfaces can have constructors; abstract classes cannot',
            'Abstract classes cannot contain methods',
        ],
        correctIndex: 1,
        explanation: 'Java supports single class inheritance (one abstract class) but multiple interface implementation, which is why interfaces are favored for type contracts.',
        xp: 20,
    },
    {
        id: 'java-7',
        category: 'java',
        difficulty: 'Hard',
        prompt: 'What is the Java Memory Model (JMM) primarily concerned with?',
        options: [
            'Garbage collection tuning',
            'The visibility and ordering rules for shared memory across threads',
            'The size of the heap',
            'The file format of .class files',
        ],
        correctIndex: 1,
        explanation: 'The JMM defines how threads interact with memory: visibility of writes, ordering of reads/writes, and the happens-before relationship that volatile and synchronized establish.',
        xp: 30,
    },
    {
        id: 'java-8',
        category: 'java',
        difficulty: 'Hard',
        prompt: 'What does a `synchronized` block guarantee?',
        options: [
            'Mutual exclusion on the monitor lock and a happens-before relationship',
            'Faster execution of the block',
            'That the block cannot throw exceptions',
            'That the block runs on the main thread',
        ],
        correctIndex: 0,
        explanation: 'synchronized acquires the monitor lock, providing mutual exclusion and a happens-before edge so changes by one thread are visible to the next thread acquiring the same lock.',
        xp: 30,
    },
    {
        id: 'java-9',
        category: 'java',
        difficulty: 'Easy',
        prompt: 'Which keyword is used to create an object in Java?',
        options: [
            'create',
            'new',
            'object',
            'instance',
        ],
        correctIndex: 1,
        explanation: 'The new keyword allocates memory and creates an object of a class.',
        xp: 10,
    },
    {
        id: 'java-10',
        category: 'java',
        difficulty: 'Easy',
        prompt: 'Which collection stores unique elements in Java?',
        options: [
            'ArrayList',
            'LinkedList',
            'HashSet',
            'Vector',
        ],
        correctIndex: 2,
        explanation: 'HashSet stores only unique elements and does not maintain insertion order.',
        xp: 10,
    },
    {
        id: 'java-11',
        category: 'java',
        difficulty: 'Medium',
        prompt: 'What is method overriding in Java?',
        options: [
            'Defining a method with the same signature in a subclass',
            'Creating multiple methods with different parameters',
            'Changing the return type of a method',
            'Calling a parent class method',
        ],
        correctIndex: 0,
        explanation: 'Method overriding allows a subclass to provide its own implementation of an inherited method, enabling runtime polymorphism.',
        xp: 20,
    },
    {
        id: 'java-12',
        category: 'java',
        difficulty: 'Medium',
        prompt: 'Which OOP principle allows exposing only essential details while hiding implementation?',
        options: [
            'Inheritance',
            'Polymorphism',
            'Abstraction',
            'Encapsulation',
        ],
        correctIndex: 2,
        explanation: 'Abstraction hides implementation details and exposes only the necessary functionality.',
        xp: 20,
    },

    {
        id: 'java-13',
        category: 'java',
        difficulty: 'Hard',
        prompt: 'Which OOP principle allows the same interface to have multiple implementations?',
        options: [
            'Encapsulation',
            'Inheritance',
            'Polymorphism',
            'Abstraction',
        ],
        correctIndex: 2,
        explanation: 'Polymorphism allows the same method call to behave differently depending on the object\'s runtime type.',
        xp: 30,
    },
    {
        id: 'java-14',
        category: 'java',
        difficulty: 'Hard',
        prompt: 'Which statement about constructors in Java is correct?',
        options: [
            'Constructors can have return types',
            'Constructors can be inherited',
            'Constructors initialize newly created objects and have no return type',
            'Constructors must always be public',
        ],
        correctIndex: 2,
        explanation: 'Constructors are special methods without a return type used to initialize objects. They are not inherited.',
        xp: 30,
    },
    {
        id: 'java-15',
        category: 'java',
        difficulty: 'Hard',
        prompt: 'Which statement correctly differentiates compile-time and runtime polymorphism?',
        options: [
            'Method overloading is runtime polymorphism and overriding is compile-time polymorphism',
            'Method overloading is compile-time polymorphism and overriding is runtime polymorphism',
            'Both are runtime polymorphism',
            'Both are compile-time polymorphism',
        ],
        correctIndex: 1,
        explanation: 'Method overloading is resolved by the compiler (compile-time), while method overriding is resolved by the JVM at runtime.',
        xp: 30,
    },
];
