import type { Question } from '../types';

export const javascriptQuestions: Question[] = [
    {
        id: 'js-1',
        category: 'javascript',
        difficulty: 'Easy',
        prompt: 'Which keyword declares a block-scoped variable that can be reassigned?',
        options: ['var', 'let', 'const', 'static'],
        correctIndex: 1,
        explanation: 'let is block-scoped and reassignable. var is function-scoped; const is block-scoped but not reassignable.',
        xp: 10,
    },
    {
        id: 'js-2',
        category: 'javascript',
        difficulty: 'Easy',
        prompt: 'What does `typeof null` return?',
        options: ['"null"', '"undefined"', '"object"', '"number"'],
        correctIndex: 2,
        explanation: 'This is a long-standing JavaScript quirk: typeof null returns "object" because of how early implementations stored type tags.',
        xp: 10,
    },
    {
        id: 'js-3',
        category: 'javascript',
        difficulty: 'Easy',
        prompt: 'Which method converts a JSON string into a JavaScript value?',
        options: ['JSON.stringify()', 'JSON.parse()', 'JSON.toObject()', 'JSON.decode()'],
        correctIndex: 1,
        explanation: 'JSON.parse() takes a JSON string and returns the corresponding JavaScript object/value. JSON.stringify() does the reverse.',
        xp: 10,
    },
    {
        id: 'js-4',
        category: 'javascript',
        difficulty: 'Medium',
        prompt: 'What is the output: `console.log(0.1 + 0.2 === 0.3)`?',
        options: ['true', 'false', 'TypeError', 'undefined'],
        correctIndex: 1,
        explanation: 'Floating-point arithmetic: 0.1 + 0.2 yields 0.30000000000000004 in IEEE 754, so strict equality with 0.3 is false.',
        xp: 20,
    },
    {
        id: 'js-5',
        category: 'javascript',
        difficulty: 'Medium',
        prompt: 'What does the `this` keyword refer to inside a normal (non-arrow) function called as `obj.foo()`?',
        options: [
            'The global object always',
            'The object on which the function was called (obj)',
            'The function itself',
            'undefined in strict mode always',
        ],
        correctIndex: 1,
        explanation: 'In a normal function, `this` is determined by the call site. Calling obj.foo() binds `this` to obj at call time.',
        xp: 20,
    },
    {
        id: 'js-6',
        category: 'javascript',
        difficulty: 'Medium',
        prompt: 'What is a closure?',
        options: [
            'A function bundled with its surrounding lexical scope',
            'A way to close a WebSocket connection',
            'A sealed class in JavaScript',
            'A syntax for finalizing garbage collection',
        ],
        correctIndex: 0,
        explanation: 'A closure is a function plus the variables from its enclosing lexical scope, which it continues to access even after that scope has returned.',
        xp: 20,
    },
    {
        id: 'js-7',
        category: 'javascript',
        difficulty: 'Hard',
        prompt: 'What is the output of this event-loop snippet?\n`console.log(1); setTimeout(() => console.log(2)); Promise.resolve().then(() => console.log(3)); console.log(4);`',
        options: ['1 2 3 4', '1 4 3 2', '1 4 2 3', '1 3 4 2'],
        correctIndex: 1,
        explanation: 'Sync code logs 1 and 4 first. Microtasks (Promise.then) run before macrotasks (setTimeout), so 3 prints before 2. Order: 1, 4, 3, 2.',
        xp: 30,
    },
    {
        id: 'js-8',
        category: 'javascript',
        difficulty: 'Hard',
        prompt: 'Which statement about `==` vs `===` is correct?',
        options: [
            '== performs type coercion; === checks value and type without coercion',
            'Both coerce types; === is just faster',
            '=== only works on primitive types',
            '== is deprecated and throws in strict mode',
        ],
        correctIndex: 0,
        explanation: '== applies Abstract Equality with type coercion. === applies Strict Equality: no coercion, different types are always unequal.',
        xp: 30,
    },
    {
        id: 'js-9',
        category: 'javascript',
        difficulty: 'Easy',
        prompt: 'Which method is used to add an element at the end of an array?',
        options: [
            'push()',
            'pop()',
            'shift()',
            'unshift()',
        ],
        correctIndex: 0,
        explanation: 'push() appends one or more elements to the end of an array and returns the new length.',
        xp: 10,
    },
    {
        id: 'js-10',
        category: 'javascript',
        difficulty: 'Easy',
        prompt: 'Which value is considered falsy in JavaScript?',
        options: [
            '"0"',
            '[]',
            '{}',
            'null',
        ],
        correctIndex: 3,
        explanation: 'Falsy values include false, 0, "", null, undefined, NaN, and 0n. Empty arrays and objects are truthy.',
        xp: 10,
    },

    {
        id: 'js-11',
        category: 'javascript',
        difficulty: 'Medium',
        prompt: 'What is the purpose of async and await in JavaScript?',
        options: [
            'To create classes',
            'To write asynchronous code in a synchronous-looking style',
            'To improve loop performance',
            'To replace promises completely',
        ],
        correctIndex: 1,
        explanation: 'async/await simplifies working with Promises by making asynchronous code easier to read and maintain.',
        xp: 20,
    },
    {
        id: 'js-12',
        category: 'javascript',
        difficulty: 'Medium',
        prompt: 'What is event bubbling?',
        options: [
            'Events propagate from child elements to parent elements',
            'Events propagate from parent to child only',
            'Events execute in random order',
            'Events stop automatically after execution',
        ],
        correctIndex: 0,
        explanation: 'By default, DOM events bubble from the target element up through its ancestors.',
        xp: 20,
    },

    {
        id: 'js-13',
        category: 'javascript',
        difficulty: 'Hard',
        prompt: 'What will be the output?\nconst obj = { a: 1 }; const copy = obj; copy.a = 5; console.log(obj.a);',
        options: [
            '1',
            '5',
            'undefined',
            'TypeError',
        ],
        correctIndex: 1,
        explanation: 'Objects are assigned by reference. Both obj and copy point to the same object.',
        xp: 30,
    },
    {
        id: 'js-14',
        category: 'javascript',
        difficulty: 'Hard',
        prompt: 'Which statement about the JavaScript event loop is correct?',
        options: [
            'Macrotasks always execute before microtasks',
            'Microtasks execute before the next macrotask',
            'Promises execute after setTimeout callbacks',
            'The event loop executes only synchronous code',
        ],
        correctIndex: 1,
        explanation: 'After synchronous code completes, all queued microtasks (like Promise callbacks) run before the next macrotask such as setTimeout.',
        xp: 30,
    },
    {
        id: 'js-15',
        category: 'javascript',
        difficulty: 'Hard',
        prompt: 'What is the difference between shallow copy and deep copy?',
        options: [
            'There is no difference',
            'A shallow copy copies nested objects by reference, while a deep copy creates independent nested copies',
            'A deep copy is only possible using JSON.parse()',
            'A shallow copy duplicates every nested object',
        ],
        correctIndex: 1,
        explanation: 'A shallow copy duplicates only the first level, whereas nested objects remain shared. A deep copy recursively duplicates nested structures.',
        xp: 30,
    },
];
