import type { Question } from '../types';

export const networksQuestions: Question[] = [
    {
        id: 'net-1',
        category: 'networks',
        difficulty: 'Easy',
        prompt: 'How many layers are in the OSI model?',
        options: ['4', '5', '7', '8'],
        correctIndex: 2,
        explanation: 'The OSI reference model has 7 layers: Physical, Data Link, Network, Transport, Session, Presentation, Application.',
        xp: 10,
    },
    {
        id: 'net-2',
        category: 'networks',
        difficulty: 'Easy',
        prompt: 'Which protocol is connection-oriented and reliable?',
        options: ['UDP', 'TCP', 'ICMP', 'ARP'],
        correctIndex: 1,
        explanation: 'TCP establishes a connection (3-way handshake) and provides reliable, ordered delivery with retransmission. UDP is connectionless and best-effort.',
        xp: 10,
    },
    {
        id: 'net-3',
        category: 'networks',
        difficulty: 'Easy',
        prompt: 'What does an IP address identify?',
        options: [
            'A specific network interface/host on a network',
            'A running process',
            'A port number',
            'A physical cable',
        ],
        correctIndex: 0,
        explanation: 'An IP address identifies a host interface on a network. A port (with the IP) then identifies a specific service/process on that host.',
        xp: 10,
    },
    {
        id: 'net-4',
        category: 'networks',
        difficulty: 'Medium',
        prompt: 'What is the purpose of DNS?',
        options: [
            'Translate human-readable domain names to IP addresses',
            'Encrypt web traffic',
            'Assign IP addresses dynamically',
            'Route packets between subnets',
        ],
        correctIndex: 0,
        explanation: 'The Domain Name System resolves names like example.com to IP addresses so applications can connect using memorable hostnames.',
        xp: 20,
    },
    {
        id: 'net-5',
        category: 'networks',
        difficulty: 'Medium',
        prompt: 'What does a subnet mask do?',
        options: [
            'Splits an IP address into network and host portions',
            'Encrypts part of the IP packet',
            'Counts the number of hops to a destination',
            'Assigns a MAC address to a host',
        ],
        correctIndex: 0,
        explanation: 'The subnet mask (or CIDR prefix length) distinguishes the network part of an IP from the host part, enabling routing and subnetting.',
        xp: 20,
    },
    {
        id: 'net-6',
        category: 'networks',
        difficulty: 'Medium',
        prompt: 'What is the three-way handshake used for?',
        options: [
            'Establishing a TCP connection (SYN, SYN-ACK, ACK)',
            'Encrypting an HTTPS session',
            'Resolving a DNS query',
            'Assigning a DHCP lease',
        ],
        correctIndex: 0,
        explanation: 'TCP connection setup exchanges SYN, SYN-ACK, and ACK between client and server to synchronize sequence numbers before data transfer.',
        xp: 20,
    },
    {
        id: 'net-7',
        category: 'networks',
        difficulty: 'Hard',
        prompt: 'What does NAT (Network Address Translation) do?',
        options: [
            'Maps private IP addresses to a public IP to share a single external address',
            'Translates domain names to IPs',
            'Encrypts packets end-to-end',
            'Assigns MAC addresses to devices',
        ],
        correctIndex: 0,
        explanation: 'NAT rewrites source/destination IPs (and ports) at a router so many private-hosts can share one public IP, conserving IPv4 space and hiding internal topology.',
        xp: 30,
    },
    {
        id: 'net-8',
        category: 'networks',
        difficulty: 'Hard',
        prompt: 'Why does TCP use sequence numbers?',
        options: [
            'To reassemble out-of-order segments and detect duplicates/loss',
            'To encrypt the payload',
            'To limit bandwidth',
            'To compress headers',
        ],
        correctIndex: 0,
        explanation: 'Sequence numbers let the receiver order segments, detect gaps for retransmission, and discard duplicates — the backbone of TCP reliable, in-order delivery.',
        xp: 30,
    },
    {
        id: 'net-9',
        category: 'networks',
        difficulty: 'Easy',
        prompt: 'Which protocol is primarily used to securely browse websites?',
        options: [
            'HTTP',
            'HTTPS',
            'FTP',
            'SMTP',
        ],
        correctIndex: 1,
        explanation: 'HTTPS is HTTP over TLS/SSL, providing encrypted communication between the client and server.',
        xp: 10,
    },
    {
        id: 'net-10',
        category: 'networks',
        difficulty: 'Easy',
        prompt: 'Which device forwards packets between different networks?',
        options: [
            'Hub',
            'Switch',
            'Router',
            'Repeater',
        ],
        correctIndex: 2,
        explanation: 'Routers operate at the Network Layer and forward packets between different networks.',
        xp: 10,
    },

    {
        id: 'net-11',
        category: 'networks',
        difficulty: 'Medium',
        prompt: 'What is the primary difference between HTTP and HTTPS?',
        options: [
            'HTTPS encrypts communication using TLS/SSL',
            'HTTP is faster because it uses TCP',
            'HTTPS uses UDP',
            'There is no difference',
        ],
        correctIndex: 0,
        explanation: 'HTTPS uses TLS/SSL encryption, making data transfer secure against interception.',
        xp: 20,
    },
    {
        id: 'net-12',
        category: 'networks',
        difficulty: 'Medium',
        prompt: 'Which protocol automatically assigns IP addresses to devices on a network?',
        options: [
            'DNS',
            'DHCP',
            'SMTP',
            'ARP',
        ],
        correctIndex: 1,
        explanation: 'DHCP dynamically assigns IP addresses, subnet masks, gateways, and DNS servers to clients.',
        xp: 20,
    },

    {
        id: 'net-13',
        category: 'networks',
        difficulty: 'Hard',
        prompt: 'Which OSI layer is responsible for end-to-end communication and error recovery?',
        options: [
            'Network Layer',
            'Transport Layer',
            'Session Layer',
            'Presentation Layer',
        ],
        correctIndex: 1,
        explanation: 'The Transport Layer provides reliable end-to-end communication using protocols like TCP.',
        xp: 30,
    },
    {
        id: 'net-14',
        category: 'networks',
        difficulty: 'Hard',
        prompt: 'Why does TCP implement flow control?',
        options: [
            'To prevent the sender from overwhelming the receiver',
            'To encrypt transmitted packets',
            'To improve DNS lookup speed',
            'To reduce IP address usage',
        ],
        correctIndex: 0,
        explanation: 'Flow control ensures the sender transmits data at a rate the receiver can process, preventing buffer overflow.',
        xp: 30,
    },
    {
        id: 'net-15',
        category: 'networks',
        difficulty: 'Hard',
        prompt: 'Which protocol translates an IP address into a MAC address within a local network?',
        options: [
            'DNS',
            'ARP',
            'DHCP',
            'ICMP',
        ],
        correctIndex: 1,
        explanation: 'ARP (Address Resolution Protocol) maps IPv4 addresses to MAC addresses on a local network.',
        xp: 30,
    },
];
