import type { Question } from '../types';

export const osQuestions: Question[] = [
    {
        id: 'os-1',
        category: 'os',
        difficulty: 'Easy',
        prompt: 'What is a process?',
        options: [
            'A running instance of a program with its own memory space',
            'A single CPU instruction',
            'A type of hardware device',
            'A network connection',
        ],
        correctIndex: 0,
        explanation: 'A process is a program in execution, with its own address space, resources, and at least one thread of control.',
        xp: 10,
    },
    {
        id: 'os-2',
        category: 'os',
        difficulty: 'Easy',
        prompt: 'What is the main purpose of a scheduler?',
        options: [
            'To decide which process/thread runs on the CPU and when',
            'To compile source code',
            'To encrypt files at rest',
            'To manage the firewall',
        ],
        correctIndex: 0,
        explanation: 'The scheduler picks the next ready process to run, aiming for fairness, throughput, and responsiveness according to the scheduling policy.',
        xp: 10,
    },
    {
        id: 'os-3',
        category: 'os',
        difficulty: 'Easy',
        prompt: 'Which memory management technique lets a process use more memory than physically available?',
        options: ['Caching', 'Virtual memory / paging', 'Compression', 'Mirroring'],
        correctIndex: 1,
        explanation: 'Virtual memory (via paging/swapping) maps logical addresses to physical frames and can page data in/out of disk, so a process virtual address space can exceed RAM.',
        xp: 10,
    },
    {
        id: 'os-4',
        category: 'os',
        difficulty: 'Medium',
        prompt: 'What is a deadlock?',
        options: [
            'A situation where two or more processes wait forever for each other resources',
            'A program that locked itself with a mutex',
            'A crashed kernel',
            'A process with no CPU time',
        ],
        correctIndex: 0,
        explanation: 'A deadlock is a cyclic wait among processes for resources, satisfying the four Coffman conditions: mutual exclusion, hold-and-wait, no preemption, circular wait.',
        xp: 20,
    },
    {
        id: 'os-5',
        category: 'os',
        difficulty: 'Medium',
        prompt: 'What is the difference between a thread and a process?',
        options: [
            'Threads share memory within a process; processes have separate memory spaces',
            'Threads are slower than processes',
            'Processes share memory; threads do not',
            'There is no difference',
        ],
        correctIndex: 0,
        explanation: 'Threads of the same process share code/data/heap (cheap context switches) but have separate stacks/registers. Processes have isolated address spaces.',
        xp: 20,
    },
    {
        id: 'os-6',
        category: 'os',
        difficulty: 'Medium',
        prompt: 'What is a context switch?',
        options: [
            'Saving one process state and loading another so the CPU can run it',
            'Switching from kernel mode to user mode only',
            'Changing the file permissions',
            'Reloading the OS',
        ],
        correctIndex: 0,
        explanation: 'A context switch stores the current process CPU state (registers, PC, MMU) and restores another process state, allowing multitasking. It has non-trivial overhead.',
        xp: 20,
    },
    {
        id: 'os-7',
        category: 'os',
        difficulty: 'Hard',
        prompt: 'Which of the four Coffman conditions is typically broken to prevent deadlocks?',
        options: [
            'Circular wait (e.g. by imposing a total resource ordering)',
            'Mutual exclusion',
            'The existence of processes',
            'The existence of memory',
        ],
        correctIndex: 0,
        explanation: 'Deadlock prevention breaks one Coffman condition; circular wait is the most practical to break by ordering all resource types and requesting them in order.',
        xp: 30,
    },
    {
        id: 'os-8',
        category: 'os',
        difficulty: 'Hard',
        prompt: 'What is the dining philosophers problem a model for?',
        options: [
            'Resource sharing and deadlock/synchronization among concurrent processes',
            'CPU scheduling fairness',
            'Page replacement algorithms',
            'Disk scheduling',
        ],
        correctIndex: 0,
        explanation: 'Dijkstra dining philosophers illustrates mutual exclusion, deadlock, and starvation in concurrent resource sharing, motivating solutions like resource ordering or a waiter.',
        xp: 30,
    },
    {
        id: 'os-9',
        category: 'os',
        difficulty: 'Easy',
        prompt: 'Which CPU scheduling algorithm executes the process that arrives first?',
        options: [
            'Round Robin',
            'Shortest Job First',
            'First Come First Serve (FCFS)',
            'Priority Scheduling',
        ],
        correctIndex: 2,
        explanation: 'FCFS executes processes in the order they arrive in the ready queue.',
        xp: 10,
    },
    {
        id: 'os-10',
        category: 'os',
        difficulty: 'Easy',
        prompt: 'What is the purpose of paging in an operating system?',
        options: [
            'To divide memory into fixed-size pages for efficient memory management',
            'To improve network speed',
            'To schedule CPU processes',
            'To compress files',
        ],
        correctIndex: 0,
        explanation: 'Paging divides logical memory into pages and physical memory into frames, eliminating external fragmentation.',
        xp: 10,
    },

    {
        id: 'os-11',
        category: 'os',
        difficulty: 'Medium',
        prompt: 'Which scheduling algorithm assigns a fixed time slice to each process?',
        options: [
            'FCFS',
            'Round Robin',
            'Shortest Job First',
            'Priority Scheduling',
        ],
        correctIndex: 1,
        explanation: 'Round Robin gives every process a fixed time quantum, ensuring fairness in time-sharing systems.',
        xp: 20,
    },
    {
        id: 'os-12',
        category: 'os',
        difficulty: 'Medium',
        prompt: 'What is a semaphore used for?',
        options: [
            'Memory allocation',
            'Process synchronization',
            'Disk scheduling',
            'Virtual memory management',
        ],
        correctIndex: 1,
        explanation: 'Semaphores are synchronization primitives used to coordinate access to shared resources between concurrent processes or threads.',
        xp: 20,
    },

    {
        id: 'os-13',
        category: 'os',
        difficulty: 'Hard',
        prompt: 'What is thrashing in an operating system?',
        options: [
            'Excessive CPU usage due to too many interrupts',
            'Excessive paging causing poor system performance',
            'A deadlock between multiple processes',
            'Corruption of file system metadata',
        ],
        correctIndex: 1,
        explanation: 'Thrashing occurs when the system spends more time swapping pages between memory and disk than executing processes.',
        xp: 30,
    },
    {
        id: 'os-14',
        category: 'os',
        difficulty: 'Hard',
        prompt: 'Which page replacement algorithm replaces the page that has not been used for the longest time?',
        options: [
            'FIFO',
            'LRU',
            'Optimal',
            'Random',
        ],
        correctIndex: 1,
        explanation: 'Least Recently Used (LRU) replaces the page that has not been accessed for the longest period.',
        xp: 30,
    },
    {
        id: 'os-15',
        category: 'os',
        difficulty: 'Hard',
        prompt: 'Which condition is necessary for a race condition to occur?',
        options: [
            'Multiple threads or processes access shared data concurrently without proper synchronization',
            'Only one process is running',
            'The CPU has multiple cores',
            'The system uses virtual memory',
        ],
        correctIndex: 0,
        explanation: 'Race conditions occur when concurrent execution accesses shared data without synchronization, leading to unpredictable results.',
        xp: 30,
    },
];
