import type { Question } from '../types';

export const pythonQuestions: Question[] = [
    {
        id: 'py-1',
        category: 'python',
        difficulty: 'Easy',
        prompt: 'What is the correct way to create a function in Python?',
        options: ['function myFunc():', 'def myFunc():', 'func myFunc():', 'fn myFunc():'],
        correctIndex: 1,
        explanation: 'Python uses the `def` keyword followed by the function name and parameters to define functions.',
        xp: 10,
    },
    {
        id: 'py-2',
        category: 'python',
        difficulty: 'Easy',
        prompt: 'Which data structure is ordered, mutable, and uses square brackets?',
        options: ['tuple', 'list', 'set', 'dict'],
        correctIndex: 1,
        explanation: 'A list is ordered and mutable, written with square brackets []. Tuples are immutable; sets are unordered; dicts hold key-value pairs.',
        xp: 10,
    },
    {
        id: 'py-3',
        category: 'python',
        difficulty: 'Easy',
        prompt: 'How do you start a single-line comment in Python?',
        options: ['//', '/*', '#', '--'],
        correctIndex: 2,
        explanation: 'Python uses the # symbol for single-line comments. Triple-quoted strings are used for multi-line/docstrings.',
        xp: 10,
    },
    {
        id: 'py-4',
        category: 'python',
        difficulty: 'Medium',
        prompt: 'What is a list comprehension?',
        options: [
            'A compact syntax to build a list from an iterable with optional filtering',
            'A way to understand long lists at runtime',
            'A method that sorts a list in place',
            'A library for parsing CSV files',
        ],
        correctIndex: 0,
        explanation: 'A list comprehension like [x*2 for x in xs if x > 0] builds a new list by applying an expression and an optional filter to an iterable.',
        xp: 20,
    },
    {
        id: 'py-5',
        category: 'python',
        difficulty: 'Medium',
        prompt: 'What does the `__init__` method do?',
        options: [
            'It is the constructor that initializes a newly created object',
            'It imports a module',
            'It deletes an object',
            'It starts the garbage collector',
        ],
        correctIndex: 0,
        explanation: '__init__ is the initializer called right after instance creation to set up attributes. (The actual creator is __new__; __init__ just initializes.)',
        xp: 20,
    },
    {
        id: 'py-6',
        category: 'python',
        difficulty: 'Medium',
        prompt: 'What is the GIL?',
        options: [
            'A lock that lets only one thread execute Python bytecode at a time (in CPython)',
            'A graphics library for Python',
            'A global import logger',
            'A garbage collection interface',
        ],
        correctIndex: 0,
        explanation: 'The Global Interpreter Lock in CPython serializes execution of Python bytecode among threads, which limits CPU-bound multi-threading (I/O threads can still release it).',
        xp: 20,
    },
    {
        id: 'py-7',
        category: 'python',
        difficulty: 'Hard',
        prompt: 'What is the difference between `is` and `==`?',
        options: [
            '`is` checks object identity; `==` checks value equality',
            'They are identical',
            '`is` checks value equality; `==` checks identity',
            '`is` only works with numbers',
        ],
        correctIndex: 0,
        explanation: '`is` tests whether two references point to the same object (identity). `==` tests equality of value via __eq__. Two equal-valued objects may be different objects.',
        xp: 30,
    },
    {
        id: 'py-8',
        category: 'python',
        difficulty: 'Hard',
        prompt: 'What does a decorator do?',
        options: [
            'It takes a function and returns a replacement function, applied with @ syntax',
            'It adds styling to console output',
            'It marks a class as abstract',
            'It deletes attributes at runtime',
        ],
        correctIndex: 0,
        explanation: 'A decorator is a callable that wraps another callable to extend or modify its behavior. @decorator above a function applies it at definition time.',
        xp: 30,
    },
    {
        id: 'py-9',
        category: 'python',
        difficulty: 'Easy',
        prompt: 'Which keyword is used to handle exceptions in Python?',
        options: [
            'catch',
            'try',
            'throw',
            'finally',
        ],
        correctIndex: 1,
        explanation: 'Exceptions are handled using try and except blocks in Python.',
        xp: 10,
    },
    {
        id: 'py-10',
        category: 'python',
        difficulty: 'Easy',
        prompt: 'Which built-in function returns the number of elements in a list?',
        options: [
            'count()',
            'length()',
            'size()',
            'len()',
        ],
        correctIndex: 3,
        explanation: 'The len() function returns the total number of elements in a collection.',
        xp: 10,
    },

    {
        id: 'py-11',
        category: 'python',
        difficulty: 'Medium',
        prompt: 'What is a lambda function in Python?',
        options: [
            'A named function',
            'An anonymous function defined using the lambda keyword',
            'A function that runs in parallel',
            'A built-in sorting function',
        ],
        correctIndex: 1,
        explanation: 'Lambda functions are anonymous, single-expression functions commonly used with map(), filter(), and sorted().',
        xp: 20,
    },
    {
        id: 'py-12',
        category: 'python',
        difficulty: 'Medium',
        prompt: 'What is the difference between a list and a tuple?',
        options: [
            'Lists are immutable and tuples are mutable',
            'Lists are mutable while tuples are immutable',
            'There is no difference',
            'Tuples are slower than lists',
        ],
        correctIndex: 1,
        explanation: 'Lists can be modified after creation, whereas tuples are immutable.',
        xp: 20,
    },

    {
        id: 'py-13',
        category: 'python',
        difficulty: 'Hard',
        prompt: 'What is a generator in Python?',
        options: [
            'A function that returns all values at once',
            'A function that yields values one at a time using yield',
            'A special type of class',
            'A built-in sorting algorithm',
        ],
        correctIndex: 1,
        explanation: 'Generators produce values lazily using the yield keyword, making them memory efficient for large datasets.',
        xp: 30,
    },
    {
        id: 'py-14',
        category: 'python',
        difficulty: 'Hard',
        prompt: 'Why should mutable objects not be used as default function arguments?',
        options: [
            'They cannot be modified',
            'The same object is reused across function calls, leading to unexpected behavior',
            'Python raises a syntax error',
            'They consume too much memory',
        ],
        correctIndex: 1,
        explanation: 'Default arguments are evaluated only once, so mutable defaults like lists can retain changes between function calls.',
        xp: 30,
    },
    {
        id: 'py-15',
        category: 'python',
        difficulty: 'Hard',
        prompt: 'Which statement about Python dictionaries is correct?',
        options: [
            'Dictionary keys must be hashable',
            'Dictionary keys can only be strings',
            'Dictionaries maintain duplicate keys',
            'Dictionary values must be immutable',
        ],
        correctIndex: 0,
        explanation: 'Dictionary keys must be immutable (hashable) so Python can efficiently locate values using hashing.',
        xp: 30,
    },
];
