import type { Question } from '../types';

export const reactQuestions: Question[] = [
    {
        id: 'react-1',
        category: 'react',
        difficulty: 'Easy',
        prompt: 'What does JSX stand for?',
        options: ['Java Syntax Extension', 'JavaScript XML', 'JSON Extended', 'Java Standard XML'],
        correctIndex: 1,
        explanation: 'JSX is a syntax extension for JavaScript that looks similar to XML/HTML and compiles to React.createElement calls.',
        xp: 10,
    },
    {
        id: 'react-2',
        category: 'react',
        difficulty: 'Easy',
        prompt: 'Which hook lets you add React state to a function component?',
        options: ['useEffect', 'useState', 'useMemo', 'useRef'],
        correctIndex: 1,
        explanation: 'useState returns a stateful value and an updater function, allowing function components to hold local state.',
        xp: 10,
    },
    {
        id: 'react-3',
        category: 'react',
        difficulty: 'Easy',
        prompt: 'What is the Virtual DOM?',
        options: [
            'A direct copy of the browser DOM in C++',
            'An in-memory representation of the real DOM used for efficient updates',
            'A browser API for SVG rendering',
            'A WebAssembly module bundled with React',
        ],
        correctIndex: 1,
        explanation: 'The Virtual DOM is a lightweight in-memory tree that React diffs against the previous version to compute minimal real-DOM mutations.',
        xp: 10,
    },
    {
        id: 'react-4',
        category: 'react',
        difficulty: 'Medium',
        prompt: 'When does useEffect with an empty dependency array run?',
        options: [
            'After every render',
            'Only after the first render',
            'Never — it is invalid syntax',
            'Only when the component unmounts',
        ],
        correctIndex: 1,
        explanation: 'An empty dependency array means the effect has no reactive dependencies, so it runs once after the initial mount (and its cleanup runs on unmount).',
        xp: 20,
    },
    {
        id: 'react-5',
        category: 'react',
        difficulty: 'Medium',
        prompt: 'Why is a "key" prop important when rendering a list of elements?',
        options: [
            'It styles list items automatically',
            'It helps React identify which items change, are added, or are removed',
            'It is required by the HTML spec for <li> tags',
            'It encrypts list data for security',
        ],
        correctIndex: 1,
        explanation: 'Keys give elements a stable identity so React can reconcile list reorders efficiently instead of re-creating every item.',
        xp: 20,
    },
    {
        id: 'react-6',
        category: 'react',
        difficulty: 'Medium',
        prompt: 'What does useReducer do that useState does not?',
        options: [
            'It manages state with a reducer function for complex state transitions',
            'It stores state in localStorage automatically',
            'It makes state immutable by compile-time checks',
            'It connects the component to Redux',
        ],
        correctIndex: 0,
        explanation: 'useReducer centralizes state logic in a reducer (state, action) => nextState function, which is cleaner than many useStates for complex, related state.',
        xp: 20,
    },
    {
        id: 'react-7',
        category: 'react',
        difficulty: 'Hard',
        prompt: 'A child component re-renders on every parent render even though its props are unchanged. What is the best fix?',
        options: [
            'Wrap the child in React.memo',
            'Convert the parent to a class component',
            'Move the child into a separate <Suspense> boundary',
            'Add the child to useReducer',
        ],
        correctIndex: 0,
        explanation: 'React.memo shallow-compares props; if they are unchanged it skips re-rendering the child. This is the standard fix for prop-stable children that re-render needlessly.',
        xp: 30,
    },
    {
        id: 'react-8',
        category: 'react',
        difficulty: 'Hard',
        prompt: 'You call a state setter inside a component body (not inside an event handler or effect). What happens?',
        options: [
            'React throws a "Cannot update during render" warning and may infinite-loop',
            'Nothing — it is perfectly normal',
            'The component is converted to a class automatically',
            'The setter is ignored until the next event',
        ],
        correctIndex: 0,
        explanation: 'Calling a setter during render triggers a re-render during the current render pass, which React warns about and which can cause an infinite loop unless guarded.',
        xp: 30,
    },
    {
        id: 'react-9',
        category: 'react',
        difficulty: 'Easy',
        prompt: 'Which hook is used to perform side effects in a React component?',
        options: [
            'useMemo',
            'useEffect',
            'useState',
            'useRef',
        ],
        correctIndex: 1,
        explanation: 'useEffect is used for side effects such as API calls, subscriptions, timers, and DOM updates.',
        xp: 10,
    },
    {
        id: 'react-10',
        category: 'react',
        difficulty: 'Easy',
        prompt: 'What is the purpose of props in React?',
        options: [
            'To store component state',
            'To pass data from parent to child components',
            'To create CSS styles',
            'To handle routing',
        ],
        correctIndex: 1,
        explanation: 'Props allow parent components to pass data and callbacks to child components.',
        xp: 10,
    },

    {
        id: 'react-11',
        category: 'react',
        difficulty: 'Medium',
        prompt: 'What is the purpose of useRef?',
        options: [
            'To trigger component re-renders',
            'To store mutable values without causing re-renders',
            'To fetch API data',
            'To manage global state',
        ],
        correctIndex: 1,
        explanation: 'useRef stores mutable values or DOM references while avoiding unnecessary re-renders.',
        xp: 20,
    },
    {
        id: 'react-12',
        category: 'react',
        difficulty: 'Medium',
        prompt: 'Why is lifting state up used in React?',
        options: [
            'To improve CSS styling',
            'To share state between multiple components through a common parent',
            'To increase rendering speed',
            'To replace React Context',
        ],
        correctIndex: 1,
        explanation: 'Lifting state up moves shared state to the nearest common ancestor so multiple child components stay synchronized.',
        xp: 20,
    },

    {
        id: 'react-13',
        category: 'react',
        difficulty: 'Hard',
        prompt: 'What is the primary purpose of useMemo?',
        options: [
            'To memoize expensive computations and avoid unnecessary recalculations',
            'To manage routing',
            'To replace useState',
            'To perform API requests',
        ],
        correctIndex: 0,
        explanation: 'useMemo caches the result of expensive calculations until one of its dependencies changes.',
        xp: 30,
    },
    {
        id: 'react-14',
        category: 'react',
        difficulty: 'Hard',
        prompt: 'When should React Context API be preferred?',
        options: [
            'For sharing global data like theme or authenticated user across many components',
            'For styling components',
            'For replacing every useState hook',
            'Only for API requests',
        ],
        correctIndex: 0,
        explanation: 'Context API helps avoid prop drilling when multiple components require the same shared data.',
        xp: 30,
    },
    {
        id: 'react-15',
        category: 'react',
        difficulty: 'Hard',
        prompt: 'Why is useCallback commonly used with React.memo?',
        options: [
            'To prevent unnecessary recreation of callback functions passed as props',
            'To improve CSS rendering',
            'To fetch API data faster',
            'To replace useEffect',
        ],
        correctIndex: 0,
        explanation: 'useCallback memoizes callback functions, preventing unnecessary child component re-renders when used with React.memo.',
        xp: 30,
    },
];
