import type { Question } from '../types';

export const sqlQuestions: Question[] = [
    {
        id: 'sql-1',
        category: 'sql',
        difficulty: 'Easy',
        prompt: 'Which SQL statement retrieves data from a table?',
        options: ['FETCH', 'SELECT', 'GET', 'RETRIEVE'],
        correctIndex: 1,
        explanation: 'SELECT is the standard SQL statement to query rows from one or more tables.',
        xp: 10,
    },
    {
        id: 'sql-2',
        category: 'sql',
        difficulty: 'Easy',
        prompt: 'Which clause filters rows returned by a query?',
        options: ['WHERE', 'FILTER', 'HAVING', 'GROUP BY'],
        correctIndex: 0,
        explanation: 'WHERE filters individual rows before grouping. HAVING filters groups after GROUP BY.',
        xp: 10,
    },
    {
        id: 'sql-3',
        category: 'sql',
        difficulty: 'Easy',
        prompt: 'Which keyword sorts the result set?',
        options: ['SORT BY', 'ORDER BY', 'GROUP BY', 'ARRANGE'],
        correctIndex: 1,
        explanation: 'ORDER BY sorts the final result set by one or more columns, with optional ASC/DESC.',
        xp: 10,
    },
    {
        id: 'sql-4',
        category: 'sql',
        difficulty: 'Medium',
        prompt: 'What is the difference between INNER JOIN and LEFT JOIN?',
        options: [
            'INNER JOIN returns only matching rows; LEFT JOIN returns all left rows plus matches (NULLs where no match)',
            'They are identical',
            'LEFT JOIN only works on numeric columns',
            'INNER JOIN is faster because it skips indexes',
        ],
        correctIndex: 0,
        explanation: 'INNER JOIN keeps only rows with a match in both tables. LEFT (OUTER) JOIN keeps every row from the left table and NULL-fills the right side when there is no match.',
        xp: 20,
    },
    {
        id: 'sql-5',
        category: 'sql',
        difficulty: 'Medium',
        prompt: 'What does an aggregate function like COUNT() require to produce per-group results?',
        options: ['A WHERE clause', 'A GROUP BY clause', 'An ORDER BY clause', 'A UNION'],
        correctIndex: 1,
        explanation: 'When you aggregate and also want per-group results, GROUP BY defines the grouping columns; the aggregate is computed for each group.',
        xp: 20,
    },
    {
        id: 'sql-6',
        category: 'sql',
        difficulty: 'Medium',
        prompt: 'What does a primary key guarantee about its column(s)?',
        options: [
            'Uniqueness and non-nullability for every row',
            'That the column stores encrypted data',
            'That the column is always an integer',
            'That the column can be updated only by admins',
        ],
        correctIndex: 0,
        explanation: 'A primary key enforces NOT NULL and uniqueness, identifying each row. It also creates an index for fast lookups.',
        xp: 20,
    },
    {
        id: 'sql-7',
        category: 'sql',
        difficulty: 'Hard',
        prompt: 'What is the difference between WHERE and HAVING?',
        options: [
            'WHERE filters rows before grouping; HAVING filters groups after aggregation',
            'They are the same and interchangeable',
            'HAVING runs before WHERE',
            'WHERE can only be used with JOINs',
        ],
        correctIndex: 0,
        explanation: 'WHERE is applied to individual rows before GROUP BY. HAVING is applied to groups after aggregation, so it can reference aggregate functions like COUNT().',
        xp: 30,
    },
    {
        id: 'sql-8',
        category: 'sql',
        difficulty: 'Hard',
        prompt: 'What does a correlated subquery do?',
        options: [
            'It references a column from the outer query, re-evaluating per outer row',
            'It runs once and caches its result',
            'It is a subquery with no FROM clause',
            'It cannot reference any table',
        ],
        correctIndex: 0,
        explanation: 'A correlated subquery depends on the outer query row, so it executes once per outer row. This is powerful but can be expensive compared to joins.',
        xp: 30,
    },
    {
        id: 'sql-9',
        category: 'sql',
        difficulty: 'Easy',
        prompt: 'Which SQL statement is used to insert a new row into a table?',
        options: [
            'ADD',
            'INSERT INTO',
            'CREATE',
            'UPDATE',
        ],
        correctIndex: 1,
        explanation: 'INSERT INTO adds one or more new rows into a table.',
        xp: 10,
    },
    {
        id: 'sql-10',
        category: 'sql',
        difficulty: 'Easy',
        prompt: 'Which SQL command removes all rows from a table but keeps the table structure?',
        options: [
            'DELETE',
            'DROP',
            'TRUNCATE',
            'REMOVE',
        ],
        correctIndex: 2,
        explanation: 'TRUNCATE removes all rows quickly while preserving the table structure.',
        xp: 10,
    },

    {
        id: 'sql-11',
        category: 'sql',
        difficulty: 'Medium',
        prompt: 'Which SQL constraint ensures that a column cannot contain duplicate values?',
        options: [
            'NOT NULL',
            'CHECK',
            'UNIQUE',
            'DEFAULT',
        ],
        correctIndex: 2,
        explanation: 'The UNIQUE constraint ensures all values in a column are distinct.',
        xp: 20,
    },
    {
        id: 'sql-12',
        category: 'sql',
        difficulty: 'Medium',
        prompt: 'What is the purpose of the DISTINCT keyword?',
        options: [
            'Sorts the result',
            'Removes duplicate rows from the result set',
            'Groups records',
            'Deletes duplicate records from the table',
        ],
        correctIndex: 1,
        explanation: 'DISTINCT returns only unique rows from the query result.',
        xp: 20,
    },

    {
        id: 'sql-13',
        category: 'sql',
        difficulty: 'Hard',
        prompt: 'Which SQL function is commonly used to assign rankings within a result set?',
        options: [
            'COUNT()',
            'ROW_NUMBER()',
            'AVG()',
            'SUM()',
        ],
        correctIndex: 1,
        explanation: 'ROW_NUMBER() is a window function that assigns a unique sequential number to each row.',
        xp: 30,
    },
    {
        id: 'sql-14',
        category: 'sql',
        difficulty: 'Hard',
        prompt: 'What is the main advantage of using indexes in SQL?',
        options: [
            'They reduce storage space',
            'They speed up query performance',
            'They automatically normalize tables',
            'They eliminate duplicate rows',
        ],
        correctIndex: 1,
        explanation: 'Indexes improve read/query performance by allowing the database to locate rows efficiently, though they slightly slow down inserts and updates.',
        xp: 30,
    },
    {
        id: 'sql-15',
        category: 'sql',
        difficulty: 'Hard',
        prompt: 'Which statement about SQL window functions is correct?',
        options: [
            'They perform calculations across related rows without collapsing the result set',
            'They always return a single row',
            'They permanently modify table data',
            'They can only be used with GROUP BY',
        ],
        correctIndex: 0,
        explanation: 'Window functions like ROW_NUMBER(), RANK(), and DENSE_RANK() calculate values across a set of rows while keeping individual rows in the output.',
        xp: 30,
    },
];
