import type { Question } from '../types';

export const typescriptQuestions: Question[] = [
    {
        id: 'ts-1',
        category: 'typescript',
        difficulty: 'Easy',
        prompt: 'Which keyword defines a custom type alias in TypeScript?',
        options: ['interface', 'type', 'typedef', 'struct'],
        correctIndex: 1,
        explanation: 'The `type` keyword creates a type alias. `interface` also defines a shape but is specifically for object/class contracts.',
        xp: 10,
    },
    {
        id: 'ts-2',
        category: 'typescript',
        difficulty: 'Easy',
        prompt: 'What does the `?` in `{ name?: string }` mean?',
        options: [
            'The property is required and must be a string',
            'The property is optional and may be undefined',
            'The property is a query parameter',
            'The property is a wildcard type',
        ],
        correctIndex: 1,
        explanation: 'A `?` marks a property optional: it can be present with a string value, or absent (implicitly undefined).',
        xp: 10,
    },
    {
        id: 'ts-3',
        category: 'typescript',
        difficulty: 'Easy',
        prompt: 'Which type represents "no value" (vs. "no value yet")?',
        options: ['undefined', 'null', 'void', 'never'],
        correctIndex: 1,
        explanation: '`null` is an intentional absence of value; `undefined` means a value has not been assigned yet. `void` is for function returns; `never` is for unreachable code.',
        xp: 10,
    },
    {
        id: 'ts-4',
        category: 'typescript',
        difficulty: 'Medium',
        prompt: 'What does `unknown` enforce that `any` does not?',
        options: [
            'No difference — they are identical',
            'You must narrow/check an `unknown` value before using it',
            '`unknown` allows any operation without checks',
            '`unknown` only works at compile time and is erased to null',
        ],
        correctIndex: 1,
        explanation: '`unknown` is the type-safe counterpart of `any`: you cannot perform operations on it until you narrow it via typeof, instanceof, or a type guard.',
        xp: 20,
    },
    {
        id: 'ts-5',
        category: 'typescript',
        difficulty: 'Medium',
        prompt: 'What is a generic in TypeScript?',
        options: [
            'A variable for types that lets you write reusable, type-safe components',
            'A way to delete types at runtime',
            'A deprecated keyword for global variables',
            'A keyword that disables type checking for a file',
        ],
        correctIndex: 0,
        explanation: 'Generics (e.g. `function id<T>(x: T): T`) parameterize types so the same code works for many types while preserving type safety.',
        xp: 20,
    },
    {
        id: 'ts-6',
        category: 'typescript',
        difficulty: 'Medium',
        prompt: 'What does `as const` do to an object literal?',
        options: [
            'Freezes the object at runtime',
            'Makes every property readonly and infers the narrowest literal types',
            'Converts the object to a const enum',
            'Marks the object as immutable in localStorage',
        ],
        correctIndex: 1,
        explanation: '`as const` tells the compiler to infer readonly properties with literal types (e.g. `{ kind: "click" }` not `{ kind: string }`). It does not freeze at runtime.',
        xp: 20,
    },
    {
        id: 'ts-7',
        category: 'typescript',
        difficulty: 'Hard',
        prompt: 'What is a conditional type, e.g. `T extends U ? X : Y`?',
        options: [
            'A type that chooses X or Y based on whether T is assignable to U',
            'A runtime if-statement for types',
            'A deprecated syntax replaced by enums',
            'A way to throw type errors at compile time',
        ],
        correctIndex: 0,
        explanation: 'Conditional types select between two types based on a type relationship check (extends), and are core to building utilities like Exclude and Extract.',
        xp: 30,
    },
    {
        id: 'ts-8',
        category: 'typescript',
        difficulty: 'Hard',
        prompt: 'What does the `infer` keyword do inside a conditional type?',
        options: [
            'It declares a type variable that captures a type from the matched type',
            'It guesses a type at runtime via reflection',
            'It logs the inferred type to the console',
            'It disables strict mode for the current line',
        ],
        correctIndex: 0,
        explanation: '`infer R` inside `extends ... ? ...` introduces a type variable R that captures part of the input type, enabling patterns like ReturnType<T> = T extends (...a: any[]) => infer R ? R : never.',
        xp: 30,
    },
    {
        id: 'ts-9',
        category: 'typescript',
        difficulty: 'Easy',
        prompt: 'Which keyword is used to define an interface in TypeScript?',
        options: [
            'interface',
            'type',
            'class',
            'implements',
        ],
        correctIndex: 0,
        explanation: 'The interface keyword defines the structure (shape) of an object or class.',
        xp: 10,
    },
    {
        id: 'ts-10',
        category: 'typescript',
        difficulty: 'Easy',
        prompt: 'What is the purpose of an enum in TypeScript?',
        options: [
            'To define a collection of named constants',
            'To create arrays',
            'To declare interfaces',
            'To store JSON objects',
        ],
        correctIndex: 0,
        explanation: 'Enums provide a way to define a set of named constant values, improving readability and maintainability.',
        xp: 10,
    },

    {
        id: 'ts-11',
        category: 'typescript',
        difficulty: 'Medium',
        prompt: 'What is a union type in TypeScript?',
        options: [
            'A type that can hold values of multiple specified types',
            'A type that combines multiple interfaces into one object',
            'A collection of arrays',
            'A runtime JavaScript feature',
        ],
        correctIndex: 0,
        explanation: 'Union types allow a variable to hold one of several specified types, e.g., string | number.',
        xp: 20,
    },
    {
        id: 'ts-12',
        category: 'typescript',
        difficulty: 'Medium',
        prompt: 'What is a type assertion in TypeScript?',
        options: [
            'A way to tell the compiler to treat a value as a specific type',
            'A runtime type conversion',
            'A method for validating JSON',
            'A way to disable type checking',
        ],
        correctIndex: 0,
        explanation: 'Type assertions inform the compiler about a value\'s type without changing the runtime behavior.',
        xp: 20,
    },

    {
        id: 'ts-13',
        category: 'typescript',
        difficulty: 'Hard',
        prompt: 'Which utility type makes all properties of an interface optional?',
        options: [
            'Readonly<T>',
            'Partial<T>',
            'Required<T>',
            'Pick<T>',
        ],
        correctIndex: 1,
        explanation: 'Partial<T> constructs a type where every property is optional.',
        xp: 30,
    },
    {
        id: 'ts-14',
        category: 'typescript',
        difficulty: 'Hard',
        prompt: 'What is the purpose of the keyof operator?',
        options: [
            'Returns a union of property names of a type',
            'Returns all values of an object',
            'Creates a new interface',
            'Defines generic constraints',
        ],
        correctIndex: 0,
        explanation: 'keyof produces a union of an object type\'s property names, useful in generic programming.',
        xp: 30,
    },
    {
        id: 'ts-15',
        category: 'typescript',
        difficulty: 'Hard',
        prompt: 'Which statement about TypeScript is correct?',
        options: [
            'TypeScript types exist only at compile time and are removed during transpilation',
            'TypeScript types are available at runtime',
            'TypeScript replaces JavaScript in the browser',
            'TypeScript code runs directly without compilation',
        ],
        correctIndex: 0,
        explanation: 'TypeScript performs static type checking during compilation, and the generated JavaScript contains no type information.',
        xp: 30,
    },
];
